apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    app: svcmysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: svcmysql
    tier: mysql
  #clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: svcmysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-mysql
  labels:
    app: svcmysql
spec:
  selector:
    matchLabels:
      app: svcmysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: svcmysql
        tier: mysql
    spec:
      containers:
      - image: docker.io/library/mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
          # valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #    key: password
        - name: MYSQL_DATABASE
          value: sql
        - name: MYSQL_USER
          value: sql
        - name: MYSQL_PASSWORD
          value: mysql
          # valueFrom:
          #  secretKeyRef:
          #    name: mysql-pass
          #    key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
